### ISSUE TITLE
Dependency unavailable due to Bintray shutdown

### ISSUE THREAD

**Issue by rmarquis** [Dominaezzz/kotlin-imgui#24]
Because of [bintray shutdown](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), kotlin-imgui is now unavailable as a dependency .

It would be great to publish in another repo, or on Github.

**Comment by Dominaezzz** [comment]
`0.1.9` has been published to GitHub packages. See README for instructions. Let me know if this works for you.

**Comment by rmarquis** [comment]
Yes, it now works perfectly. I've been able to launch my first Kotlin + imgui demo.
Thank you so much!
