### ISSUE TITLE
Finished with nonzero exit code.

### ISSUE THREAD

**Issue by Kesanov** [Dominaezzz/kotlin-imgui#26]
I have created a simple Hello-World app:

```
import com.imgui.*

fun main() {
    with(ImGui) {
        text("Hello, world!")
   }
}
```

Yet, it doesn't show anything on screen and exits with the following message:
```
Execution failed for task ':runDebugExecutableNative'.
> Process 'command 'D:\hello-imgui\build\bin\native\debugExecutable\hello-imgui.exe'' finished with non-zero exit value -1073741819
```

**Comment by Dominaezzz** [comment]
check this out https://github.com/Dominaezzz/kotlin-imgui/issues/22#issuecomment-797750989

**Comment by Kesanov** [comment]
Oh. That's a surprisingly huge amount of configuration required, for even a small program.

**Comment by Dominaezzz** [comment]
The cost of flexibility I guess.

It shouldn't be that much code. At least in the context of graphics programming, it's pretty small I'd say.

Can I ask what you're using imgui for?

**Comment by Kesanov** [comment]
I am writing a small download manager with file-tree view.

I agree that flexibility is important. But it would be nice to have at least 2 APIs: full-fledged & simple - which would hide this complexity until you actually need it.

**Comment by Dominaezzz** [comment]
Looks like you got past this.
