### ISSUE TITLE
How to arrange items ?

### ISSUE THREAD

**Issue by RageshAntony** [Dominaezzz/kotlin-imgui#29]
The example are arranging the views vertically only 

How to arrange them as different layout ?

For example this image :
![image](https://user-images.githubusercontent.com/36100215/137624838-85d90c6c-e87e-411f-bdc9-19439234e8ca.png)

**Comment by Dominaezzz** [comment]
This is a question for upstream https://github.com/ocornut/imgui.

**Comment by RageshAntony** [comment]
> question for upstream

Sorry. I am bad in English and Tech. I can't understand your answer. Will you please elaborate ?

**Comment by Dominaezzz** [comment]
I'm telling you to ask you question there.
My library is just a wrapper around https://github.com/ocornut/imgui.

**Comment by Dominaezzz** [comment]
Feel free to reopen if you have more questions.
