### ISSUE TITLE
Upgrade kotlin-imgui to 1.3.70

### ISSUE THREAD

**Issue by nlbuescher** [Dominaezzz/kotlin-imgui#5]
just tried the new version of kgl and got hung up on the same ABI problem with this lib.

**Comment by nlbuescher** [comment]
I noticed a push to upgrade to kotlin 1.3.71, but the maven artifacts haven't received this change (although the actions have published the changes). Could this be because of the tag? version still says 0.1.0

**Comment by Dominaezzz** [comment]
There's a button on BinTray I have to click, to say the published version should go through.
The artefacts should be available now.

**Comment by nlbuescher** [comment]
Works now with 0.1.1. Thanks for your help!
